exports.STATE_TYPE = {SLEEP:0,IN_HOME:1,GOTO_WORK:2,WORKING:3,GO_HOME:4};

exports.ACTION_DESCRIPTIONS = {GET_UP:0,GOTO_OFFICE:1,GO_HOME:2,
	                          GOTO_BED:3,ARRIVE_OFFICE:4,ARRIVE_HOME:5};